server:
  port: 8080
spring:
  application:
    name: "msa-authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: r2dbc:mysql://alex:123456@192.168.1.10:3306/pragma
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/users"